/**
 * 完整 Claude Desktop 简体中文翻译数据集 (550 条官方 HashKey 全覆盖)
 */
const dict = {
  "++hDyegrrU": "是否将“{fileName}”添加到新对话？",
  "+/cwsayrqk": "实际大小",
  "+3KiTtWq89": "移除“{folderName}”并停止 {count, plural, one {# 个远程会话} other {# 个远程会话}}？",
  "+7sd9hoyZA": "复制",
  "+Fax0wMvjs": "将创客/硬件设备连接至 Claude",
  "+NwlCZ9GfR": "您尚未登录。请登录以访问扩展目录。",
  "+ZfCaxCk0y": "导入完成",
  "+rUDCO79Js": "正在扫描 5 秒…",
  "+vRFr4+yQ/": "是否允许 Claude 控制 {apps}？",
  "/2yTD12Rf+": "远程控制已关闭",
  "/6Btt89krf": "忽略",
  "/PgA81GVOD": "编辑",
  "/Rj+1w2qLm": "团队 (Team)",
  "/bRGKhnXQ6": "发现新版本，将自动下载并安装。",
  "/eO5H6Jz2q": "另一个 Claude 实例已在运行中",
  "/m8y3SO8Pb": "刷新",
  "/waNG9D45T": "离开",
  "06KK1e0srf": "所有权修复未完成。在此问题解决前，自动更新可能无法正常工作。您可以下次重试。",
  "075Zq8hhWT": "取消",
  "07vFNkmKKB": "设备工具访问权限",
  "0AmZKbkN6W": "这将清除当前未运行的 Cowork 协同会话的缓存和临时文件。会话工作区中的文件不会受到影响。",
  "0Cs12/GF/H": "{skipped, plural, one {已跳过 # 个选定的文件夹。} other {已跳过 # 个选定的文件夹。}}",
  "0Ezrt/NNqd": "选择 Claude 数据文件夹",
  "0GT0SIETlE": "取消",
  "0NmcPHSn/L": "所有权修复失败",
  "0eJo9Vzuvt": "是否信任 {cwd} 并启动代码会话？",
  "0tZLEYF8mJ": "开发者",
  "0vttuC3ieI": "加载远程 Claude.ai",
  "1BYhB06oNf": "Chrome 扩展会话已过期。请在 Chrome 中打开 Claude 扩展重新登录，然后重试。",
  "1Gc0Drz87C": "打开",
  "1HUTYwndT2": "窗口",
  "1lmEcH0QkK": "Cowork 需要 QEMU。请使用“{installCommand}”进行安装，然后重启 Claude。",
  "1nSZez10qJ": "扩展预览失败",
  "1o7ejsqYGi": "扩展安装失败",
  "1oMaxu+1Ai": "使用额度 · {used}",
  "1p920W6EQA": "是否打开此链接？",
  "1yqIF4NCWV": "您稍后在 Claude Code 中信任的文件夹将自动添加。您可以在“设置 -> Claude Code”中随时移除任何文件夹。",
  "2/2BMRHIA/": "调试",
  "26ig1HTaOj": "此版本的 Cowork 尚不支持磁盘清理。请重启应用后重试。",
  "2OTyZOnjhc": "由于以下错误，无法预览该扩展。请确保 DXT 文件有效并重试。{errorMessage}",
  "2Spx55hKaC": "此功能需要 macOS 13.0 或更高版本",
  "2aiB9NK3YP": "部分项目无法移除。",
  "2cplZXFjPL": "重新安装工作区",
  "2kVHmyDyr/": "Claude 需要您的输入以继续",
  "2x2ParVoQo": "硬件助手与创客设备",
  "38E9oKs/ky": "删除 Cowork 虚拟机会话并重启…",
  "39r88rYBHt": "提交反馈 - Claude",
  "3ML3xT+gEV": "重做",
  "3Y2OGh5Jbr": "取消",
  "3unrKzH4zB": "复制",
  "45E6u2ngvv": "{mA}mA",
  "47FYwba+bI": "取消",
  "4KjH9o80Fc": "正在检查更新…",
  "4MLbtbVfJv": "剪切",
  "4SR4k2XYM1": "刚刚更新",
  "4WuqlpXz7I": "Claude 需要修复文件所有权以便自动更新正常工作。",
  "4XmExNuKUb": "故障排除",
  "4bODbpeosC": "在此计算机上发现 {count, plural, one {# 个 Claude Code CLI 会话} other {# 个 Claude Code CLI 会话}}，{count, plural, one {该会话不在} other {这些会话不在}}您的会话列表中。这包括从终端启动的会话，可能包含来自其他组织的会话、早期版本的会话或在旧版应用中删除的会话。导入的会话将保留对话历史和上次运行时的权限模式，但归档状态和已授予权限无法恢复。",
  "4duD3GQOwb": "选择数据文件夹",
  "4utN6mPwyo": "您的组织拒绝了访问。请联系管理员。",
  "4wArDWCxOC": "删除虚拟机会话并重启",
  "4xrT8niZlX": "此设备请求了未加密的连接。数据正在以明文发送，这意味着附近的其他设备可以轻松窃听。",
  "5DUIVR3fVi": "关于…",
  "5WUg3uZhO2": "{others, plural, one {已跳过 # 个文件夹，因为它受保护、包含受保护文件或为主文件夹。} other {已跳过 # 个文件夹，因为它们受保护、包含受保护文件或为主文件夹。}}",
  "5fDh29sjSc": "无法重新加载 MCP 配置。请查看日志获取更多详情。",
  "5pB1BMiwbL": "添加文件夹",
  "65XqOcfujo": "取消",
  "65oRnf2FWj": "使用情况截图已复制到剪贴板",
  "65rgkIccNj": "当前无法显示 {device} 的访问请求；请稍后重试。",
  "6Blr2N4E48": "删除并重启",
  "6X84YaYFCl": "选择以下路径内的文件夹：{roots}",
  "6yv8ytK4El": "请检查您的网络连接",
  "71dtHvbhEs": "等待 Claude",
  "7Arh/jSQPF": "这将打开 {appName} 以撰写发送给 {email} 的邮件。",
  "7BkU20KRFT": "Cowork 需要 Windows 10 内部版本 2004 或更高版本。请更新操作系统以使用此功能。",
  "7DG1YUwIAv": "启用 Cowork 虚拟机调试日志",
  "7G27hVrdBJ": "安装",
  "7fdcqxofEs": "退出",
  "7hTxy0HBbC": "已跳过部分文件夹",
  "7rB147Yq4f": "是否移动到“应用程序”文件夹？",
  "82jNv3f0M7": "学习拼写",
  "8ABQf0B1B0": "预览",
  "8E+11x8wT5": "运行的会话过多",
  "8FQgAh4OBl": "Cowork 需要硬件虚拟化 (KVM)，但此设备上不可用。请在固件设置中启用虚拟化以使用此功能。",
  "8Fl1Xq7Kht": "远程控制",
  "8Ru8/2NkQP": "扩展预览失败",
  "8W7dNhwk37": "{extensionDetails} 这些扩展将保持安装状态，如果您切换到允许这些扩展的组织，可以重新启用它们。您也可以在“设置”中将其删除。",
  "8YQEOfuaGO": "全选",
  "8v5YXS3Pty": "未释放任何空间。",
  "9+afSO9e/t": "检查更新失败：{error}",
  "9DyIMdlUEL": "访问日志出错",
  "9GRz7bC+rr": "配置第三方推理路由…",
  "9HIsz1Smer": "已连接",
  "9IxjUqgX9u": "{action, select, connect {连接连接器} disconnect {断开连接器} apply {查看配置} other {确认}}",
  "9OBj0jX9+a": "无法打开链接",
  "9OFtp2pNVO": "取消",
  "9Tp+r6VHjz": "当前无法添加此文件夹。请稍后重试。",
  "9aJv5Q6PQw": "跳过反馈并重新安装",
  "9k6UwFX1VZ": "无法检查更新",
  "AAoe5u9j1e": "是否要安装 {extensionName}？"
};

module.exports = dict;
